### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by ghost** [uakfdotb/wc3connect#2]
```
root@kd10841:/home/wc3connect/bin# java -jar wc3cd.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/entgaming/wc3connectd/WCServer : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: net.entgaming.wc3connectd.WCServer. Program will exit.
root@kd10841:/home/wc3connect/bin# php genkeystore.php
PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php5/cli/conf.d/ming.ini on line 1 in Unknown on line 0
PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php5/cli/conf.d/ps.ini on line 1 in Unknown on line 0
This tool generates a keystore that you can use to sign your applet. Note that it will be a self-signed certificate.
PHP Fatal error:  Call to undefined function readline() in /home/wc3connect/bin/genkeystore.php on line 4
root@kd10841:/home/wc3connect/bin# php signer.php
PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php5/cli/conf.d/ming.ini on line 1 in Unknown on line 0
PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php5/cli/conf.d/ps.ini on line 1 in Unknown on line 0
This tool will sign WC3Connect.jar to create SWC3Connect.jar.
PHP Fatal error:  Call to undefined function readline() in /home/wc3connect/bin/signer.php on line 4
```

What did i miss here & or what should i do to solve this issues?

**Comment by uakfdotb** [comment]
You need to upgrade your Java version, or recompile wc3connectd with your version.

**Comment by ghost** [comment]
Which is the java version you are using?
A simple apt-get update/upgrade didnt make my job :-P

```
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03)
Java HotSpot(TM) 64-Bit Server VM (build 20.1-b02, mixed mode)
```

**Comment by uakfdotb** [comment]
Probably Java 7 then. The correct solution is to compile the code with your version.

**Comment by ghost** [comment]
I probably have no knowledge on this and i dont know how and where to compile :-P

**Comment by uakfdotb** [comment]
If you don't need a JAR then just go to the wc3connect directory and run javac -classpath src:bin/lib/\* src/net/entgaming.net/wc3connectd/WCServer.java

**Comment by ghost** [comment]
Well sorry for the problems, but im still not sure what to do next :-P It seems like it was compiling now, but i dont know where the output is etc what to do now to run it.

If im going to /bin and try to start it, again the same errors does pop up.

**Comment by uakfdotb** [comment]
You need to run from the generated .class files with java -classpath src:bin/lib/\* net.entgaming.wc3connectd.WC3Server

**Comment by ghost** [comment]
Ahhh i c.
However; 

```
root@kd10841:/home/wc3connect# javac -classpath src:bin/lib/* src/net/entgaming/wc3connectd/WCServer.java
root@kd10841:/home/wc3connect# java -classpath src:bin/lib/* net.entgaming.wc3connectd.WC3Server
Exception in thread "main" java.lang.NoClassDefFoundError: net/entgaming/wc3connectd/WC3Server
Caused by: java.lang.ClassNotFoundException: net.entgaming.wc3connectd.WC3Server
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: net.entgaming.wc3connectd.WC3Server.  Program will exit.
root@kd10841:/home/wc3connect#
```

**Comment by ghost** [comment]
nvm found it, its running. Thanks so far.

**Comment by ghost** [comment]
Ok there is now still the last issue:

```
root@kd10841:/home/wc3connect/bin# php genkeystore.php
This tool generates a keystore that you can use to sign your applet. Note that it will be a self-signed certificate.
PHP Fatal error:  Call to undefined function readline() in /home/wc3connect/bin/genkeystore.php on line 4
root@kd10841:/home/wc3connect/bin# php signer.php
This tool will sign WC3Connect.jar to create SWC3Connect.jar.
PHP Fatal error:  Call to undefined function readline() in /home/wc3connect/bin/signer.php on line 4
root@kd10841:/home/wc3connect/bin# dpkg -l | grep -i 'readline'
ii  libreadline5                                           5.2-7                        GNU readline and history libraries, run-time libraries
ii  libreadline6                                           6.1-3                        GNU readline and history libraries, run-time libraries
ii  libreadline6-dev                                       6.1-3                        GNU readline and history libraries, development files
ii  readline-common                                        6.1-3                        GNU readline and history libraries, common files

```

:-/

**Comment by styla01** [comment]
This tool generates a keystore that you can use to sign your applet. Note that it will be a self-signed certificate. 
Fatal error: Call to undefined function readline() in D:\xampp\htdocs\wc3connect\genkeystore.php on line 4

how u fix this ? :)
